version: '3.4'

services:
  ece568hw2:
    image: ece568hw2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - data-volume:/var/log/erss
      - ./src:/code

volumes:
  data-volume: